<?php
use app\components\helpers\Tbl;

class m000000_000003_minute extends \yii\db\Migration
{
    public function safeUp()
    {
        $this->createTable(Tbl::minute, [
            'id'           => $this->primaryKey(2)->notNull()->unsigned(),
            'minute'       => $this->smallInteger(2)->notNull()->unsigned()->unique(),
        ], 'CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ENGINE=InnoDB');

        $this->alterColumn(Tbl::minute, 'id', $this->smallInteger(2).' UNSIGNED NOT NULL AUTO_INCREMENT');

        $this->createIndex('index_minute', Tbl::minute, 'minute');

        $this->batchInsert(Tbl::minute,
            [
                'minute',
            ],
            [
                [
                    '0',
                ],
                [
                    '1',
                ],
                [
                    '2',
                ],
                [
                    '3',
                ],
                [
                    '4',
                ],
                [
                    '5',
                ],
                [
                    '6',
                ],
                [
                    '7',
                ],
                [
                    '8',
                ],
                [
                    '9',
                ],
                [
                    '10',
                ],
                [
                    '11',
                ],
                [
                    '12',
                ],
                [
                    '13',
                ],
                [
                    '14',
                ],
                [
                    '15',
                ],
                [
                    '16',
                ],
                [
                    '17',
                ],
                [
                    '18',
                ],
                [
                    '19',
                ],
                [
                    '20',
                ],
                [
                    '21',
                ],
                [
                    '22',
                ],
                [
                    '23',
                ],
                [
                    '24',
                ],
                [
                    '25',
                ],
                [
                    '26',
                ],
                [
                    '27',
                ],
                [
                    '28',
                ],
                [
                    '29',
                ],
                [
                    '30',
                ],
                [
                    '31',
                ],
                [
                    '32',
                ],
                [
                    '33',
                ],
                [
                    '34',
                ],
                [
                    '35',
                ],
                [
                    '36',
                ],
                [
                    '37',
                ],
                [
                    '38',
                ],
                [
                    '39',
                ],
                [
                    '40',
                ],
                [
                    '41',
                ],
                [
                    '42',
                ],
                [
                    '43',
                ],
                [
                    '44',
                ],
                [
                    '45',
                ],
                [
                    '46',
                ],
                [
                    '47',
                ],
                [
                    '48',
                ],
                [
                    '49',
                ],
                [
                    '50',
                ],
                [
                    '51',
                ],
                [
                    '52',
                ],
                [
                    '53',
                ],
                [
                    '54',
                ],
                [
                    '55',
                ],
                [
                    '56',
                ],
                [
                    '57',
                ],
                [
                    '58',
                ],
                [
                    '59',
                ],
            ]
        );
    }

    public function safeDown()
    {
        $this->dropTable(Tbl::minute);
    }
}
